# Generated by Django 4.2.17 on 2025-03-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CantactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(max_length=14, verbose_name='تلفن')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name': 'ارتباط با ما',
            },
        ),
    ]
