# Generated by Django 4.2.17 on 2025-03-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cantactmodel',
            name='phone',
            field=models.BigIntegerField(max_length=14, verbose_name='تلفن'),
        ),
    ]
