# Generated by Django 4.2.17 on 2025-03-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_cantactmodel_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cantactmodel',
            name='emaill',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='cantactmodel',
            name='phonee',
            field=models.BigIntegerField(blank=True, default=2, max_length=16, verbose_name='2 تلفن'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cantactmodel',
            name='address',
            field=models.CharField(max_length=70, verbose_name='آدرس'),
        ),
    ]
