# Generated by Django 4.2.17 on 2025-03-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_cantactmodel_emaill_cantactmodel_phonee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cantactmodel',
            name='phone',
            field=models.BigIntegerField(verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='cantactmodel',
            name='phonee',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='2 تلفن'),
        ),
    ]
