# Generated by Django 4.2.17 on 2025-03-12 18:56

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_cantactmodel_phone_alter_cantactmodel_phonee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cantactmodel',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='cantactmodel',
            name='phonee',
            field=phonenumber_field.modelfields.PhoneNumberField(default=0, max_length=128, region=None, verbose_name='2 تلفن'),
            preserve_default=False,
        ),
    ]
