# Generated by Django 4.2.17 on 2025-03-13 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='شناسه یکتا')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات دسته\u200cبندی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='نویسنده')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/images/', verbose_name='تصویر مقاله')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان مقاله')),
                ('content', models.TextField(verbose_name='محتوای مقاله')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='شناسه یکتا')),
                ('status', models.BooleanField(default=True, verbose_name='وضعیت فعال')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین بروزرسانی')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-published_date'],
            },
        ),
    ]
