# Generated by Django 4.2.17 on 2025-05-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_b',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
