# Generated by Django 4.2.17 on 2025-03-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='image',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='thickness',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
