# Generated by Django 4.2.17 on 2025-03-12 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_productmodel_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductCategoryModel',
        ),
        migrations.RemoveField(
            model_name='wishlistproductmodel',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wishlistproductmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='slug',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='vahed',
            field=models.CharField(default=2, max_length=255, verbose_name='واحد'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='avg_rate',
            field=models.CharField(max_length=255, verbose_name='ابعاد'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='brief_description',
            field=models.TextField(blank=True, null=True, verbose_name='محل تحویل'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='discount_percent',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='وزن تؤری'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='thickness',
            field=models.PositiveIntegerField(default=0, verbose_name='ضخامت'),
        ),
        migrations.DeleteModel(
            name='ProductImageModel',
        ),
        migrations.DeleteModel(
            name='WishlistProductModel',
        ),
    ]
