# Generated by Django 4.2.17 on 2025-04-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_productmodel_title_alter_productmodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleDateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_string', models.CharField(help_text='تاریخ را وارد کنید (مثلاً: 1403/01/27 یا 2025-04-16)', max_length=20)),
            ],
        ),
    ]
