# Generated by Django 4.2.17 on 2025-04-16 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_simpledatemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.simpledatemodel'),
        ),
    ]
