# Generated by Django 4.2.17 on 2025-07-30 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_productmodel_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmodel',
            options={'ordering': ['-created_date'], 'verbose_name': 'لیست قیمت'},
        ),
    ]
